version: "3.9"  

services:
  astro-database:
    image: mongo:6
    container_name: astro-database
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - astro_db_data:/data/db

  quantum-backend:
    build:
      context: .
      dockerfile: src/server/Dockerfile
    container_name: quantum-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - astro-database
    environment:
      - DB_URI=mongodb://astro-database:27017/mern-minimal
      - NODE_ENV=development   

  nebula-frontend:
    build:
      context: .
      dockerfile: src/client/Dockerfile
    container_name: nebula-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - quantum-backend

volumes:
  astro_db_data:
