name: Matrix Docker Build and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build & Push ${{ matrix.service }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - quantum-backend
          - nebula-frontend
        include:
          - service: quantum-backend
            dockerfile: src/server/Dockerfile
            context: .
            tag: jovana5rova/quantum-backend:latest
          - service: nebula-frontend
            dockerfile: src/client/Dockerfile
            context: .
            tag: jovana5rova/nebula-frontend:latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push ${{ matrix.service }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ matrix.tag }}
          build-args: |
            NODE_ENV=production
